server:
  port: 80

spring:
  profiles:
  #??jdbc?redis?mail????
    active: jdbc,redis,mail
  # ??thymeleaf????
  thymeleaf:
    cache: false
  # ?????????
  messages:
    basename: i18n.logo

# MyBatis??
mybatis:
  configuration:
    #??????????
    map-underscore-to-camel-case: true
  #??MyBatis?xml??????
  mapper-locations: classpath:mapper/*.xml
  #??XML???????????????
  type-aliases-package: com.itheima.model.domain

#pagehelper????
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#???cookie????
COOKIE:
  # ??cookie?????30??
  VALIDITY: 1800

